print('\033[1;92m Pass List is There')
print('First Last')
print('First Last')
print('First')
print('First123')
print('First Last123')
print('FirstLast123')
print('First last')
print('first Last')
print('first last123')
print('firstlast123')
print('first last')
print('firstlast')
print('First last123')
print('first Last123')
print('\033[1;92m Thank For Using')
